version: "3.8"

services:
  psql_db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgres/data/pgdata
    ports:
      - 5432:5432
    container_name: postgres_container

  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - psql_db
    volumes:
      - .:/django
    image: app:django
    container_name: django_container
    command: >
      sh -c "sleep 3 && cd url_shortener &&  python3 manage.py migrate &&  python3 manage.py runserver 0.0.0.0:8000"
