# Generated by Django 4.1 on 2022-08-10 10:08

from django.db import migrations, models
import django.db.models.deletion
import redirection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="UrlData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visits", models.IntegerField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "hour",
                    models.IntegerField(
                        choices=[
                            (0, "00:00-01:59"),
                            (2, "02:00-03:59"),
                            (4, "04:00-05:59"),
                            (6, "06:00-07:59"),
                            (8, "08:00-09:59"),
                            (10, "10:00-11:59"),
                            (12, "12:00-13:59"),
                            (14, "14:00-15:59"),
                            (16, "16:00-17:59"),
                            (18, "18:00-19:59"),
                            (20, "20:00-21:59"),
                            (22, "22:00-23:59"),
                        ],
                        default=redirection.models.now_timeframe,
                        editable=False,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="redirection.country",
                        to_field="name",
                    ),
                ),
                (
                    "key",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shortener.shortenedurl",
                        to_field="key",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Urls Data",
                "ordering": ["-date", "key", "-visits"],
                "get_latest_by": "date",
            },
        ),
    ]
