# Generated by Django 4.1 on 2022-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("redirection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(default="Unknown", max_length=50, unique=True),
        ),
    ]
